<?php

namespace App\Http\Controllers\aefi;


use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use DB;
use Illuminate\Support\Str;
class AESIInsertController extends Controller
{
    public function insertaesiform1(Request $req)
	 	{
					$arr_vac_init = load_vac_init();
					$listvac_arr = $this->listvac_arr();
					$yearnow_c =  now()->year;
					$yearnow =  now()->year+543;
					$name_of_vaccine = $req->input('name_of_vaccine');
					$id_case =  $req->input ('id_case');
		            $title_name =  $req->input ('title_name');
		            $first_name =  $req->input ('first_name');
		            $sur_name =  $req->input ('sur_name');
		            $hn =  $req->input ('hn');
		            $an =  $req->input ('an');
		            $id_number =  $req->input ('id_number');
		            $marital_status =  $req->input ('marital_status');
		            $career_code =  $req->input ('career_code');
		            $congenital_disease =  $req->input ('congenital_disease');
		            $regular_medication =  $req->input ('regular_medication');
		            $house_number =  $req->input ('house_number');
		            $village_no =  $req->input ('village_no');
		            $province =  $req->input ('province');
		            $district =  $req->input ('district');
		            $subdistrict =  $req->input ('subdistrict');
		            $phone_number =  $req->input ('phone_number');
		            $parent_title_name =  $req->input ('parent_title_name');
		            $parent_first_name =  $req->input ('parent_first_name');
		            $parent_last_name =  $req->input ('parent_last_name');
		            $parent_phone_number =  $req->input ('parent_phone_number');
		            $date_of_symptoms =  $req->input ('date_of_symptoms');
		            $date_of_treatment =  $req->input ('date_of_treatment');
		            $date_of_dischrge =  $req->input ('date_of_dischrge');
		            $hospcode_treat =  $req->input ('hospcode_treat');
		            $patient_type =  $req->input ('patient_type');
		            $patient_tube =  $req->input ('patient_tube');
		            $chief_complaint =  $req->input ('chief_complaint');
		            $temp =  $req->input ('temp');
		            $rr =  $req->input ('rr');
		            $pr =  $req->input ('pr');
		            $bp =  $req->input ('bp');
		            $gcs_e =  $req->input ('gcs_e');
		            $gcs_m =  $req->input ('gcs_m');
		            $gcs_v =  $req->input ('gcs_v');
		            $pupils_l =  $req->input ('pupils_l');
		            $pupils_r =  $req->input ('pupils_r');
		            $physical_examination =  $req->input ('physical_examination');
		            $neurological_examination =  $req->input ('neurological_examination');
		            $J80 =  $req->input ('J80');
		            $U07_1 =  $req->input ('U07_1');
		            $I40 =  $req->input ('I40');
		            $I30 =  $req->input ('I30');
		            $G37_3 =  $req->input ('G37_3');
		            $G61 =  $req->input ('G61');
		            $I64 =  $req->input ('I64');
		            $G51 =  $req->input ('G51');
		            $G04 =  $req->input ('G04');
		            $G03 =  $req->input ('G03');
		            $G05_8 =  $req->input ('G05_8');
		            $D69_3 =  $req->input ('D69_3');
		            $D69 =  $req->input ('D69');
		            $M30_3 =  $req->input ('M30_3');
		            $I77_6 =  $req->input ('I77_6');
		            $L95 =  $req->input ('L95');
		            $other_immune_mediated =  $req->input ('other_immune_mediated');
		            $I80_2 =  $req->input ('I80_2');
		            $I26 =  $req->input ('I26');
		            $T69_1 =  $req->input ('T69_1');
		            $last_diagnosis =  $req->input ('last_diagnosis');
		            $text_last_diagnosis =  $req->input ('text_last_diagnosis');
		            $diagnosis =  $req->input ('diagnosis');
		            $hospcode_treat1 =  $req->input ('hospcode_treat1');
		            $text_hospcode_treat =  $req->input ('text_hospcode_treat');
		            $CXR =  $req->input ('CXR');
		            $CXR_date =  $req->input ('CXR_date');
		            $CXR_results =  $req->input ('CXR_results');
		            $CT =  $req->input ('CT');
		            $CT_body_organs =  $req->input ('CT_body_organs');
		            $CT_date =  $req->input ('CT_date');
		            $CT_results =  $req->input ('CT_results');
		            $MRI =  $req->input ('MRI');
		            $MRI_body_organs =  $req->input ('MRI_body_organs');
		            $MRI_date =  $req->input ('MRI_date');
		            $MRI_results =  $req->input ('MRI_results');
		            $EKG =  $req->input ('EKG');
		            $EKG_date =  $req->input ('EKG_date');
		            $EKG_results =  $req->input ('EKG_results');
		            $first_CBC =  $req->input ('first_CBC');
		            $first_CBC_Hct =  $req->input ('first_CBC_Hct');
		            $first_CBC_WBC =  $req->input ('first_CBC_WBC');
		            $first_CBC_Neu =  $req->input ('first_CBC_Neu');
		            $first_CBC_Lymp =  $req->input ('first_CBC_Lymp');
		            $first_CBC_Mono =  $req->input ('first_CBC_Mono');
		            $first_CBC_Eo =  $req->input ('first_CBC_Eo');
		            $first_CBC_Baso =  $req->input ('first_CBC_Baso');
		            $first_CBC_Plt_count =  $req->input ('first_CBC_Plt_count');
		            $first_blood_bhemistry_Hct =  $req->input ('first_blood_bhemistry_Hct');
		            $first_blood_bhemistry_WBC =  $req->input ('first_blood_bhemistry_WBC');
		            $first_blood_bhemistry_Neu =  $req->input ('first_blood_bhemistry_Neu');
		            $first_blood_bhemistry_Lymp =  $req->input ('first_blood_bhemistry_Lymp');
		            $first_blood_bhemistry_Mono =  $req->input ('first_blood_bhemistry_Mono');
		            $first_blood_bhemistry_Eo =  $req->input ('first_blood_bhemistry_Eo');
		            $first_blood_bhemistry_Baso =  $req->input ('first_blood_bhemistry_Baso');
		            $first_blood_bhemistry_Plt_count =  $req->input ('first_blood_bhemistry_Plt_count');
		            $cholesterol =  $req->input ('cholesterol');
		            $triglyceride =  $req->input ('triglyceride');
		            $HDL =  $req->input ('HDL');
		            $LDL =  $req->input ('LDL');
		            $PTT =  $req->input ('PTT');
		            $PT =  $req->input ('PT');
		            $TT =  $req->input ('TT');
		            $Coagulogram_other =  $req->input ('Coagulogram_other');
		            $CSF =  $req->input ('CSF');
		            $CSF_date =  $req->input ('CSF_date');
		            $CSF_nature =  $req->input ('CSF_nature');
		            $CSF_PMN =  $req->input ('CSF_PMN');
		            $CSF_Lymp =  $req->input ('CSF_Lymp');
		            $CSF_Protein =  $req->input ('CSF_Protein');
		            $CSF_sugar =  $req->input ('CSF_sugar');
		            $CSF_other =  $req->input ('CSF_other');
		            $NPS =  $req->input ('NPS');
		            $NPS_date =  $req->input ('NPS_date');
		            $NPS_PCR =  $req->input ('NPS_PCR');
		            $NPS_lab =  $req->input ('NPS_lab');
		            $19_IgM =  $req->input ('19_IgM');
		            $Serum_COVID-19_IgM1_date =  $req->input ('Serum_COVID-19_IgM1_date');
		            $Serum_COVID-19_IgM1_PCR =  $req->input ('Serum_COVID-19_IgM1_PCR');
		            $Serum_COVID-19_IgM2_lab =  $req->input ('Serum_COVID-19_IgM2_lab');
		            $Serum_COVID-19_IgM2_date =  $req->input ('Serum_COVID-19_IgM2_date');
		            $Serum_COVID-19_IgM2_PCR =  $req->input ('Serum_COVID-19_IgM2_PCR');
		            $Serum_COVID-19_IgM2_lab1 =  $req->input ('Serum_COVID-19_IgM2_lab1');
		            $Serum_COVID-19_IgG =  $req->input ('Serum_COVID-19_IgG');
		            $Serum_COVID-19_IgG1_date =  $req->input ('Serum_COVID-19_IgG1_date');
		            $Serum_COVID-19_IgG1_PCR =  $req->input ('Serum_COVID-19_IgG1_PCR');
		            $Serum_COVID-19_IgG2_lab =  $req->input ('Serum_COVID-19_IgG2_lab');
		            $Serum_COVID-19_IgG2_date =  $req->input ('Serum_COVID-19_IgG2_date');
		            $Serum_COVID-19_IgG2_PCR =  $req->input ('Serum_COVID-19_IgG2_PCR');
		            $Serum_COVID-19_IgG2_lab1 =  $req->input ('Serum_COVID-19_IgG2_lab1');
		            $other_examination =  $req->input ('other_examination');
		            $other_date_examination =  $req->input ('other_date_examination');
		            $other_saple_type =  $req->input ('other_saple_type');
		            $other_method =  $req->input ('other_method');
		            $other_examination_results =  $req->input ('other_examination_results');
		            $other_lab =  $req->input ('other_lab');
		            $covid19 =  $req->input ('covid19');
		            $othercovid19 =  $req->input ('othercovid19');
		            $inspect_covid =  $req->input ('inspect_covid');
		            $inspect_covid_results =  $req->input ('inspect_covid_results');
		            $$inspect_covid_location =  $req->input ('inspect_covid_location');
		            $inspect_covid_date =  $req->input ('inspect_covid_date');
		            $covid_close_contact =  $req->input ('covid_close_contact');
		            $contact_nature =  $req->input ('contact_nature');
		            $other_contact_nature =  $req->input ('other_contact_nature');
		            $drug_allergy =  $req->input ('drug_allergy');
		            $drug_allergy_name =  $req->input ('drug_allergy_name');
		            $allergic_vaccines =  $req->input ('allergic_vaccines');
		            $allergic_vaccines_name =  $req->input ('allergic_vaccines_name');
		            $allergy =  $req->input ('allergy');
		            $detail_allergy =  $req->input ('detail_allergy');
		            $username_reporter =  $req->input ('username_reporter');
		            $province_reporter =  $req->input ('province_reporter');
		            $region_reporter =  $req->input ('region_reporter');
		            $hospital_reporter =  $req->input ('hospital_reporter');
		            $date_entry =  $req->input ('date_entry');
		            $date_update =  $req->input ('date_update');
		            $status =  $req->input ('status');
		$data = array(
			'id_case = $id_case,
		            'title_name' = $title_name,
		            'first_name' = $first_name,
		            'sur_name' = $sur_name,
		            'hn' = $hn,
		            'an' = $an,
		            'id_number' = $id_number,
		            'marital_status' = $marital_status,
		            'career_code' = $career_code,
		            'congenital_disease' = $congenital_disease,
		            'regular_medication' = $regular_medication,
		            'house_number' = $house_number,
		            'village_no' = $village_no,
		            'province' = $province,
		            'district' = $district,
		            'subdistrict' = $subdistrict,
		            'phone_number' = $phone_number,
		            'parent_title_name' = $parent_title_name,
		            'parent_first_name' = $parent_first_name,
		            'parent_last_name' = $parent_last_name,
		            'parent_phone_number' = $parent_phone_number,
		            'date_of_symptoms' = $date_of_symptoms,
		            'date_of_treatment' = $date_of_treatment,
		            'date_of_dischrge' = $date_of_dischrge,
		            'hospcode_treat' = $hospcode_treat,
		            'patient_type' = $patient_type,
		            'patient_tube' = $patient_tube,
		            'chief_complaint' = $chief_complaint,
		            'temp' = $temp,
		            'rr' = $rr,
		            'pr' = $pr,
		            'bp' = $bp,
		            'gcs_e' = $gcs_e,
		            'gcs_m' = $gcs_m,
		            'gcs_v' = $gcs_v,
		            'pupils_l' = $pupils_l,
		            'pupils_r' = $pupils_r,
		            'physical_examination' = $physical_examination,
		            'neurological_examination' = $neurological_examination,
		            'J80' = $J80,
		            'U07_1' = $U07_1,
		            'I40' = $I40,
		            'I30' = $I30,
		            'G37_3' = $G37_3,
		            'G61' = $G61,
		            'I64' = $I64,
		            'G51' = $G51,
		            'G04' = $G04,
		            'G03' = $G03,
		            'G05_8' = $G05_8,
		            'D69_3' = $D69_3,
		            'D69' = $D69,
		            'M30_3' = $M30_3,
		            'I77_6' = $I77_6,
		            'L95' = $L95,
		            'other_immune_mediated' = $other_immune_mediated,
		            'I80_2' = $I80_2,
		            'I26' = $I26,
		            'T69_1' = $T69_1,
		            'last_diagnosis' = $last_diagnosis,
		            'text_last_diagnosis' = $text_last_diagnosis,
		            'diagnosis' = $diagnosis,
		            'hospcode_treat1' = $hospcode_treat1,
		            'text_hospcode_treat' = $text_hospcode_treat,
		            'CXR' = $CXR,
		            'CXR_date' = $CXR_date,
		            'CXR_results' = $CXR_results,
		            'CT' = $CT,
		            'CT_body_organs' = $CT_body_organs,
		            'CT_date' = $CT_date,
		            'CT_results' = $CT_results,
		            'MRI' = $MRI,
		            'MRI_body_organs' = $MRI_body_organs,
		            'MRI_date' = $MRI_date,
		            'MRI_results' = $MRI_results,
		            'EKG' = $EKG,
		            'EKG_date' = $EKG_date,
		            'EKG_results' = $EKG_results,
		            'first_CBC' = $first_CBC,
		            'first_CBC_Hct' = $first_CBC_Hct,
		            'first_CBC_WBC' = $first_CBC_WBC,
		            'first_CBC_Neu' = $first_CBC_Neu,
		            'first_CBC_Lymp' = $first_CBC_Lymp,
		            'first_CBC_Mono' = $first_CBC_Mono,
		            'first_CBC_Eo' = $first_CBC_Eo,
		            'first_CBC_Baso' = $first_CBC_Baso,
		            'first_CBC_Plt_count' = $first_CBC_Plt_count,
		            'first_blood_bhemistry_Hct' = $first_blood_bhemistry_Hct,
		            'first_blood_bhemistry_WBC' = $first_blood_bhemistry_WBC,
		            'first_blood_bhemistry_Neu' = $first_blood_bhemistry_Neu,
		            'first_blood_bhemistry_Lymp' = $first_blood_bhemistry_Lymp,
		            'first_blood_bhemistry_Mono' = $first_blood_bhemistry_Mono,
		            'first_blood_bhemistry_Eo' = $first_blood_bhemistry_Eo,
		            'first_blood_bhemistry_Baso' = $first_blood_bhemistry_Baso,
		            'first_blood_bhemistry_Plt_count' = $first_blood_bhemistry_Plt_count,
		            'cholesterol' = $cholesterol,
		            'triglyceride' = $triglyceride,
		            'HDL' = $HDL,
		            'LDL' = $LDL,
		            'PTT' = $PTT,
		            'PT' = $PT,
		            'TT' = $TT,
		            'Coagulogram_other' = $Coagulogram_other,
		            'CSF' = $CSF,
		            'CSF_date' = $CSF_date,
		            'CSF_nature' = $CSF_nature,
		            'CSF_PMN' = $CSF_PMN,
		            'CSF_Lymp' = $CSF_Lymp,
		            'CSF_Protein' = $CSF_Protein,
		            'CSF_sugar' = $CSF_sugar,
		            'CSF_other' = $CSF_other,
		            'NPS' = $NPS,
		            'NPS_date' = $NPS_date,
		            'NPS_PCR' = $NPS_PCR,
		            'NPS_lab' = $NPS_lab,
		            '19_IgM' = $19_IgM,
		            'Serum_COVID-19_IgM1_date' = $Serum_COVID-19_IgM1_date,
		            'Serum_COVID-19_IgM1_PCR' = $Serum_COVID-19_IgM1_PCR,
		            'Serum_COVID-19_IgM2_lab' = $Serum_COVID-19_IgM2_lab,
		            'Serum_COVID-19_IgM2_date' = $Serum_COVID-19_IgM2_date,
		            'Serum_COVID-19_IgM2_PCR' = $Serum_COVID-19_IgM2_PCR,
		            'Serum_COVID-19_IgM2_lab1' = $Serum_COVID-19_IgM2_lab1,
		            'Serum_COVID-19_IgG' = $Serum_COVID-19_IgG,
		            'Serum_COVID-19_IgG1_date' = $Serum_COVID-19_IgG1_date,
		            'Serum_COVID-19_IgG1_PCR' = $Serum_COVID-19_IgG1_PCR,
		            'Serum_COVID-19_IgG2_lab' = $Serum_COVID-19_IgG2_lab,
		            'Serum_COVID-19_IgG2_date' = $Serum_COVID-19_IgG2_date,
		            'Serum_COVID-19_IgG2_PCR' = $Serum_COVID-19_IgG2_PCR,
		            'Serum_COVID-19_IgG2_lab1' = $Serum_COVID-19_IgG2_lab1,
		            'other_examination' = $other_examination,
		            'other_date_examination' = $other_date_examination,
		            'other_saple_type' = $other_saple_type,
		            'other_method' = $other_method,
		            'other_examination_results' = $other_examination_results,
		            'other_lab' = $other_lab,
		            'covid19' = $covid19,
		            'othercovid19' = $othercovid19,
		            'inspect_covid' = $inspect_covid,
		            'inspect_covid_results' = $inspect_covid_results,
		            'inspect_covid_location' = $inspect_covid_location,
		            'inspect_covid_date' = $inspect_covid_date,
		            'covid_close_contact' = $covid_close_contact,
		            'contact_nature' = $contact_nature,
		            'other_contact_nature' = $other_contact_nature,
		            'drug_allergy' = $drug_allergy,
		            'drug_allergy_name' = $drug_allergy_name,
		            'allergic_vaccines' = $allergic_vaccines,
		            'allergic_vaccines_name' = $allergic_vaccines_name,
		            'allergy' = $allergy,
		            'detail_allergy' = $detail_allergy,
		            'username_reporter' = $username_reporter,
		            'province_reporter' = $province_reporter,
		            'region_reporter' = $region_reporter,
		            'hospital_reporter' = $hospital_reporter,
		            'date_entry' = $date_entry,
		            'date_update' = $date_update,
		            'status' = $status,

		);
	$res1	= DB::table('aesi_form')->insert($data);
if ($res1) {
		$name_of_vaccine = $req ->input('name_of_vaccine');
		$vaccine_volume = $req ->input('vaccine_volume');
		$route_of_vaccination = $req ->input('route_of_vaccination');
		$vaccination_site = $req ->input('vaccination_site');
		$dose = $req ->input('dose');
		$date_of_vaccination = $req ->input('date_of_vaccination');
		$time_of_vaccination = $req ->input('time_of_vaccination');
		$manufacturer =$req ->input('manufacturer');
		$lot_number = $req ->input('lot_number');
		$expiry_date = $req ->input('expiry_date');
		// $name_of_diluent = $req ->input('name_of_diluent');
		$lot_number_diluent = $req ->input('lot_number_diluent');
		$expiry_date_diluent = $req ->input('expiry_date_diluent');
		$other_manufacturer = $req ->input('other_manufacturer');
		// symotom session
		$rash = (isset($_POST['rash'])) ? $_POST['rash'] : '0';
		$erythema = $req ->input ('erythema');
		$urticaria = $req ->input ('urticaria');
		$itching = $req ->input ('itching');
		$edema = $req ->input ('edema');
		$angioedema = $req ->input ('angioedema');
		$fainting = $req ->input ('fainting');
		$hyperventilation = $req ->input ('hyperventilation');
		$syncope = $req ->input ('syncope');
		$headche = $req ->input ('headche');
		$dizziness = $req ->input ('dizziness');
		$fatigue = $req ->input ('fatigue');
		$malaise = $req ->input ('malaise');
		$dyspepsia = $req ->input ('dyspepsia');
		$diarrhea = $req ->input ('diarrhea');
		$nausea = $req ->input ('nausea');
		$vomiting = $req ->input ('vomiting');
		$abdominal_pain = $req ->input ('abdominal_pain');
		$arthalgia = $req ->input ('arthalgia');
		$myalgia = $req ->input ('myalgia');
		$fever38c = $req ->input ('fever38c');
		$swelling_at_the_injection = $req ->input ('swelling_at_the_injection');
		$swelling_beyond_nearest_joint = $req ->input ('swelling_beyond_nearest_joint');
		$lymphadenopathy = $req ->input ('lymphadenopathy');
		$lymphadenitis = $req ->input ('lymphadenitis');
		$sterile_abscess = $req ->input ('sterile_abscess');
		$bacterial_abscess = $req ->input ('bacterial_abscess');
		$febrile_convulsion = $req ->input ('febrile_convulsion');
		$afebrile_convulsion = $req ->input ('afebrile_convulsion');
		$encephalopathy = $req ->input ('encephalopathy');
		$flaccid_paralysis = $req ->input ('flaccid_paralysis');
		$spastic_paralysis = $req ->input ('spastic_paralysis');
		$hhe = $req ->input ('hhe');
		$persistent_inconsolable_crying = $req ->input ('persistent_inconsolable_crying');
		$thrombocytopenia = $req ->input ('thrombocytopenia');
		$osteomyelitis = $req ->input ('osteomyelitis');
		$toxic_shock_syndrome = $req ->input ('toxic_shock_syndrome');
		$sepsis = $req ->input ('sepsis');
		$anaphylaxis = $req ->input ('anaphylaxis');
		$other = $req ->input ('other');
		$date_of_symptoms = $req ->input ('date_of_symptoms');
		$time_of_symptoms = $req ->input ('time_of_symptoms');
		$date_of_treatment = $req ->input ('date_of_treatment');
		$time_of_treatment = $req ->input ('time_of_treatment');
		$Symptoms_details = $req ->input ('Symptoms_details');
		$text_other_seriousness_symptoms = $req ->input ('text_other_seriousness_symptoms');
		$symptoms_later_immunized = $req ->input ('symptoms_later_immunized');
		$other_symptoms_later_immunized = $req ->input ('other_symptoms_later_immunized');
		$diagnosis = $req ->input ('diagnosis');
		$seriousness_of_the_symptoms = $req ->input ('seriousness_of_the_symptoms');
		$seriousness_of_the_symptoms2 = $req ->input ('seriousness_of_the_symptoms2');
		$other_seriousness_of_the_symptoms = $req ->input ('other_seriousness_of_the_symptoms');
		$patient_status = $req ->input ('patient_status');
		$patient_status2 = $req ->input ('patient_status2');
		$funeral = $req ->input ('funeral');
		$other_address_funeral = $req ->input ('other_address_funeral');
		$transverse_myelitis = $req ->input ('transverse_myelitis');
		$adem = $req ->input ('adem');
		$acute_myocardial = $req ->input ('acute_myocardial');
		$ards = $req ->input ('ards');
		$gbs = $req ->input ('gbs');
		$date_dead = $req ->input ('date_dead');
		$symptomstatus = $req ->input ('symptomstatus');
		$chest_pain = $req ->input ('chest_pain');
		$myocarditis = $req ->input ('myocarditis');
		$heart_failure = $req ->input ('heart_failure');
		$pericarditis = $req ->input ('pericarditis');
		$sudden_cardiac_arrest = $req ->input ('sudden_cardiac_arrest');
		$covid_19 = $req ->input ('covid_19');
		$ischemic_stroke = $req ->input ('ischemic_stroke');
		$hemorrhagic_stroke = $req ->input ('hemorrhagic_stroke');
		$deep_vein_thrombosis = $req ->input ('deep_vein_thrombosis');
		$pulmonary_embolism= $req ->input ('pulmonary_embolism');
		$hypertension= $req ->input ('hypertension');
		$hypertensive_urgency= $req ->input ('hypertensive_urgency');
		$bells_palsy= $req ->input ('bells_palsy');
		$symptom_status= $req ->input ('symptom_status');
		// $time_of_reconstitution = $req ->input('time_of_reconstitution');
		// dd($date_of_vaccination,$rash);
$x=0;
	 for ($i=0; $i < count($name_of_vaccine); $i++) {
		 $data_vac[]  = [
		'id_case'=>$id_case,
		'name_of_vaccine'=>$name_of_vaccine[$i],
		'vaccine_volume'=>$vaccine_volume[$i],
		'route_of_vaccination'=>$route_of_vaccination[$i],
		'vaccination_site'=>$vaccination_site[$i],
		'dose'=>$dose[$i],
		'date_of_vaccination'=>$date_of_vaccination[$i],
		'time_of_vaccination'=>$time_of_vaccination[$i],
		'manufacturer'=>$manufacturer[$i],
		'lot_number'=>$lot_number[$i],
		'expiry_date'=>$expiry_date[$i],
		// 'name_of_diluent'=>$name_of_diluent[$i],
		'lot_number_diluent'=>$lot_number_diluent[$i],
		'expiry_date_diluent'=>$expiry_date_diluent[$i],
		'other_manufacturer'=>$other_manufacturer[$i],
		// 'time_of_reconstitution'=>$time_of_reconstitution[$i],
		// symptom session
		'date_dead'=>$date_dead[$i],
		'text_other_seriousness_symptoms'=>$text_other_seriousness_symptoms[$i],
		'rash'=>(isset($rash[$i])) ? $rash[$i]  : '0',
		'erythema'=>(isset($erythema[$i])) ? $erythema[$i]  : '0',
		'urticaria'=>(isset($urticaria[$i])) ? $urticaria[$i]  : '0',
		'itching'=>(isset($itching[$i])) ? $itching[$i]  : '0',
		'edema'=>(isset($edema[$i])) ? $edema[$i]  : '0',
		'angioedema'=>(isset($angioedema[$i])) ? $angioedema[$i]  : '0',
		'fainting'=>(isset($fainting[$i])) ? $fainting[$i]  : '0',
		'hyperventilation'=>(isset($hyperventilation[$i])) ? $hyperventilation[$i]  : '0',
		'syncope'=>(isset($syncope[$i])) ? $syncope[$i]  : '0',
		'headche'=>(isset($headche[$i])) ? $headche[$i]  : '0',
		'dizziness'=>(isset($dizziness[$i])) ? $dizziness[$i]  : '0',
		'fatigue'=>(isset($fatigue[$i])) ? $fatigue[$i]  : '0',
		'malaise'=>(isset($malaise[$i])) ? $malaise[$i]  : '0',
		'dyspepsia'=>(isset($dyspepsia[$i])) ? $dyspepsia[$i]  : '0',
		'diarrhea'=>(isset($diarrhea[$i])) ? $diarrhea[$i]  : '0',
		'nausea'=>(isset($nausea[$i])) ? $nausea[$i]  : '0',
		'vomiting'=>(isset($vomiting[$i])) ? $vomiting[$i]  : '0',
		'abdominal_pain'=>(isset($abdominal_pain[$i])) ? $abdominal_pain[$i]  : '0',
		'arthalgia'=>(isset($arthalgia[$i])) ? $arthalgia[$i]  : '0',
		'myalgia'=>(isset($myalgia[$i])) ? $myalgia[$i]  : '0',
		'fever38c'=>(isset($fever38c[$i])) ? $fever38c[$i]  : '0',
		'swelling_at_the_injection'=>(isset($swelling_at_the_injection[$i])) ? $swelling_at_the_injection[$i]  : '0',
		'swelling_beyond_nearest_joint'=>(isset($swelling_beyond_nearest_joint[$i])) ? $swelling_beyond_nearest_joint[$i]  : '0',
		'lymphadenopathy'=>(isset($lymphadenopathy[$i])) ? $lymphadenopathy[$i]  : '0',
		'lymphadenitis'=>(isset($lymphadenitis[$i])) ? $lymphadenitis[$i]  : '0',
		'sterile_abscess'=>(isset($sterile_abscess[$i])) ? $sterile_abscess[$i]  : '0',
		'bacterial_abscess'=>(isset($bacterial_abscess[$i])) ? $bacterial_abscess[$i]  : '0',
		'febrile_convulsion'=>(isset($febrile_convulsion[$i])) ? $febrile_convulsion[$i]  : '0',
		'afebrile_convulsion'=>(isset($afebrile_convulsion[$i])) ? $afebrile_convulsion[$i]  : '0',
		'encephalopathy'=>(isset($encephalopathy[$i])) ? $encephalopathy[$i]  : '0',
		'flaccid_paralysis'=>(isset($flaccid_paralysis[$i])) ? $flaccid_paralysis[$i]  : '0',
		'spastic_paralysis'=>(isset($spastic_paralysis[$i])) ? $spastic_paralysis[$i]  : '0',
		'hhe'=>(isset($hhe[$i])) ? $hhe[$i]  : '0',
		'persistent_inconsolable_crying'=>(isset($persistent_inconsolable_crying[$i])) ? $persistent_inconsolable_crying[$i]  : '0',
		'thrombocytopenia'=>(isset($thrombocytopenia[$i])) ? $thrombocytopenia[$i]  : '0',
		'osteomyelitis'=>(isset($osteomyelitis[$i])) ? $osteomyelitis[$i]  : '0',
		'toxic_shock_syndrome'=>(isset($toxic_shock_syndrome[$i])) ? $toxic_shock_syndrome[$i]  : '0',
		'sepsis'=>(isset($sepsis[$i])) ? $sepsis[$i]  : '0',
		'anaphylaxis'=>(isset($anaphylaxis[$i])) ? $anaphylaxis[$i]  : '0',
		'other'=>(isset($other[$i])) ? $other[$i]  : '0',
		'date_of_symptoms'=>$date_of_symptoms[$i],
		'time_of_symptoms'=>$time_of_symptoms[$i],
		'date_of_treatment'=>$date_of_treatment[$i],
		'time_of_treatment'=>$time_of_treatment[$i],
		'Symptoms_details'=>$Symptoms_details[$i],
		'symptoms_later_immunized'=>$symptoms_later_immunized[$i],
		'other_symptoms_later_immunized'=>$other_symptoms_later_immunized[$i],
		'diagnosis'=>$diagnosis[$i],
		'seriousness_of_the_symptoms'=>$seriousness_of_the_symptoms[$i],
		'other_seriousness_of_the_symptoms'=>$other_seriousness_of_the_symptoms[$i],
		'patient_status'=>$patient_status[$i],
		'funeral'=>$funeral[$i],
		'other_address_funeral'=>$other_address_funeral[$i],
		'transverse_myelitis' => $transverse_myelitis[$i],
		'adem' => $adem[$i],
		'acute_myocardial' => $acute_myocardial[$i],
		'ards' => $ards[$i],
		'gbs'=>$gbs[$i],
		'date_entry'=>date('Y-m-d'),
		'symptomstatus'=>$symptomstatus,
		'chest_pain'=>$chest_pain[$i],
		'myocarditis'=>$myocarditis[$i],
		'heart_failure'=>$heart_failure[$i],
		'pericarditis'=>$pericarditis[$i],
		'sudden_cardiac_arrest'=>$sudden_cardiac_arrest[$i],
		'covid_19'=>$covid_19[$i],
		'ischemic_stroke'=>$ischemic_stroke[$i],
		'hemorrhagic_stroke'=>$hemorrhagic_stroke[$i],
		'deep_vein_thrombosis'=>$deep_vein_thrombosis[$i],
		'pulmonary_embolism'=>$pulmonary_embolism[$i],
		'hypertension'=>$hypertension[$i],
		'hypertensive_urgency'=>$hypertensive_urgency[$i],
		'bells_palsy'=>$bells_palsy[$i],
		'symptom_status'=>$symptom_status[$i]
		];
		$x++;
		}
        // dd($data,$data_vac);
		 $res2= DB::table('aefi_form_1_vac')->insert($data_vac);
	}
											if ($res2) {
												$msg = " ส่งข้อมูลสำเร็จ";
												$url_rediect = "<script>alert('".$msg."'); window.location='lstaesi1';</script> ";
											}else{
												$msg = " ส่งข้อมูลไม่สำเร็จ";
												$url_rediect = "<script>alert('".$msg."'); window.location='formaesi1';</script> ";
														}
												echo $url_rediect;

}
protected function listvac_arr(){
	$arr_vac = DB::table('vac_tbl')->select('VAC_CODE','VAC_NAME_EN')->get();
	foreach ($arr_vac as  $value) {
		$arr_vac[$value->VAC_CODE] =trim($value->VAC_NAME_EN);
	}
	// dd($province_arr);
	return $arr_vac;
}
}
